---
title: "Cambios en las Creencias sobre la Meritocracia y las Preferencias por la Justicia de Mercado en el Contexto Escolar Chileno"
subtitle: "Pre-registro (versión en español)"
format: pdf
editor: source
bibliography: "../input/bib/merit-redis-school.bib"
link-citations: true
---


1. ¿Cuál es la hipótesis que se investigará?

*Proporcione una breve descripción de la teoría relevante y formule la hipótesis con la mayor precisión posible* 
    
La desigualdad económica se refiere a la distribución desigual de la riqueza, los ingresos y otros recursos y oportunidades económicas dentro de una sociedad. Existen diversas formas de justificar la desigualdad económica entre individuos y grupos, donde las percepciones acerca de la meritocracia pueden desempeñar un papel importante [@castillo_socialization_2024]. Una manera de estudiar la desigualdad económica consiste en analizar las preferencias por la justicia de mercado, entendidas como las creencias en torno a cuán justo es que quienes tienen mayores ingresos accedan en mejores condiciones a servicios sociales como salud, educación y pensiones [@lane_market_1986; @lindh_bringing_2023]. Sin embargo, la mayoría de los estudios sobre justicia de mercado se ha centrado en poblaciones adultas, dejando un conocimiento limitado acerca de los factores asociados a estas preferencias en edades más tempranas y acerca de cómo se forman [@castillo_socialization_2024]. Utilizando datos de la encuesta panel de dos olas “Educación y Meritocracia” (N=900, 2023–2024), realizada entre estudiantes de educación básica y media en Chile, este estudio profundiza en los cambios y en la influencia de las percepciones y preferencias sobre la meritocracia en el ámbito escolar y en la sociedad en general, en relación con la justicia de mercado. Dado que la meritocracia se concibe como un sistema en el cual las recompensas se distribuyen en función del esfuerzo y el talento [@young_rise_1958], la hipótesis central plantea que quienes perciban mayor meritocracia y prefieran la meritocracia tanto en la escuela como en la sociedad tenderán a exhibir mayores preferencias por la justicia de mercado.

Siguiendo el marco conceptual y de medición propuesto por Castillo et al. [-@castillo_multidimensional_2023] (véase Figura 1), operacionalizamos la meritocracia a partir de tres distinciones clave. En primer lugar, diferenciamos entre percepciones y preferencias: mientras las percepciones se refieren a cómo las personas observan los principios meritocráticos en la sociedad (es decir, lo que es), las preferencias aluden a juicios normativos sobre cómo debería funcionar idealmente la meritocracia (es decir, lo que debería ser) [@janmaat_subjective_2013]. En segundo lugar, distinguimos entre elementos meritocráticos y no meritocráticos: si bien los contactos personales y la riqueza familiar [@reynolds_perceptions_2014; @sandel_tyranny_2020] pueden parecer incompatibles con la valoración del esfuerzo y el talento, no necesariamente contradicen por completo el reconocimiento de estos factores para lograr el éxito [@young_rise_1958]. En tercer lugar, examinamos dos niveles en los cuales operan los principios meritocráticos: a nivel escolar, la meritocracia se relaciona con si el estudiantado considera que la inteligencia y el esfuerzo predicen el rendimiento académico (p. ej., buenas calificaciones) [@resh_sense_2010], mientras que a nivel social, se aborda cómo se perciben y se desean dichos principios de forma más amplia.

Por ende, se plantean las siguientes hipótesis:

  * H1: Los estudiantes con mayor percepción de meritocracia social mostrarán una mayor preferencia por la justicia de mercado.
  * H2: Los estudiantes con mayor preferencia de meritocracia social mostrarán una mayor preferencia por la justicia de mercado.
  * H3: Los estudiantes con mayor percepción de elementos sociales no meritocráticos mostrarán una menor preferencia por la justicia de mercado.
  * H4: Los estudiantes con mayor preferencia de elementos sociales no meritocráticos mostrarán una mayor preferencia por la justicia de mercado.
  * H5: Los estudiantes con mayor percepción de meritocracia escolar mostrarán una mayor preferencia por la justicia de mercado.

Finalmente, investigaciones previas señalan que los niños más pequeños suelen mostrar una preferencia por la igualdad, mientras que a medida que crecen comienzan a aceptar la desigualdad si está justificada por el mérito [@almas_fairness_2010; @baumard_preschoolers_2012]. Por tanto, se esperan diferencias en las preferencias por la justicia de mercado según el nivel escolar (básica vs. media) y a lo largo del tiempo (2023–2024). Así, se formulan dos hipótesis adicionales:

  *  H6: A medida que los estudiantes avanzan en los cursos sucesivos (efecto within) y pertenecen a cohortes más recientes (efecto between), sus preferencias por la justicia de mercado aumentarán.
  *  H7: La asociación entre las percepciones de meritocracia y las preferencias por la justicia de mercado se fortalecerá a medida que los estudiantes progresen en su escolarización (efecto within).

2.¿Cómo se operacionalizarán las variables cruciales?

*Indique exactamente cómo se medirán las variables especificadas en la hipótesis. *

Preferencias por la justicia de mercado: Nuestra variable dependiente es la justicia de mercado. Este constructo se mide a través de tres ítems que evalúan hasta qué punto los encuestados justifican que el acceso a servicios sociales (salud, pensiones y educación) deba estar condicionado por el ingreso. Los ítems son los siguientes:

- Salud: “¿Es bueno que quienes pueden pagar más tengan mejor acceso a la salud?”
- Educación: “¿Es bueno que quienes pueden pagar más tengan mejor educación?”
- Pensiones: “¿Es bueno que en Chile las personas con mayores ingresos puedan tener mejores pensiones que las personas con menores ingresos?”

En todos los casos, los encuestados indican sus preferencias utilizando una escala Likert de cuatro puntos que va desde “muy en desacuerdo” (1) hasta “muy de acuerdo” (4). Además, se incluye un indicador resumen de “preferencias por la justicia de mercado,” medido por un índice promedio de estos ítems, con valores que van de 1 a 4, donde valores más altos representan preferencias más fuertes por la justicia de mercado.

En lo referente a la meritocracia, se consideran dos variantes:

_Nivel social_

**Escala de percepciones y preferencias sobre la meritocracia social**: Las variables incluidas en el modelo de medición para las percepciones y preferencias de elementos tanto meritocráticos como no meritocráticos se operacionalizan con base en los ítems propuestos por Castillo et al. [-@castillo_multidimensional_2023]. La percepción de meritocracia se mide mediante dos ítems que indagan el nivel de acuerdo sobre si en Chile se recompensa el esfuerzo y la habilidad, mientras que las percepciones no meritocráticas se miden con dos ítems que evalúan hasta qué punto se considera que el éxito proviene de contactos personales y riqueza familiar. La preferencia por la meritocracia se mide a través de dos ítems que evalúan el grado de acuerdo con que quienes trabajan más o tienen más talento deberían recibir mayores recompensas. La preferencia por factores no meritocráticos se evalúa mediante dos indicadores que miden el grado de acuerdo con la idea de que es aceptable que quienes tengan mejores contactos o padres adinerados logren un mayor éxito. Cada ítem se respondió en una escala Likert de cuatro puntos que va de “muy en desacuerdo” (1) a “muy de acuerdo” (4).

_Nivel escolar_

**Percepción de la meritocracia escolar**: Esta variable capta la importancia percibida del esfuerzo y la inteligencia para obtener buenas calificaciones. Los ítems son: (a) “En este colegio, quienes se esfuerzan obtienen buenas notas,” (b) “En este colegio, quienes son inteligentes obtienen buenas notas,” y (c) “En este colegio, los estudiantes reciben las notas que merecen.” Las categorías de respuesta van de 1 a 4, donde 1 indica “muy en desacuerdo” y 4 “muy de acuerdo.”

3. ¿Cuál es la fuente de los datos incluidos en los análisis?

*Especifique la fuente de los datos obtenidos. También proporcione información sobre el contexto de la fuente de datos y aclare si los datos se han publicado anteriormente. En el caso de datos simulados, proporcione información sobre cómo se generaron los datos. *

El conjunto de datos que se utilizará proviene de la encuesta panel “Educación y Meritocracia” (EDUMER), llevada a cabo en Chile durante 2023 y 2024. Este estudio evaluó a estudiantes de sexto básico y primero medio de nueve colegios de la Región Metropolitana. El total de respuestas completas alcanza los 902 estudiantes. Enlace al repositorio y a la documentación [aquí](https://github.com/educacion-meritocracia/special-issue-inequality).

4. ¿Cómo se obtendrán estos datos?

*Especifique cómo se solicitarán o accederán a los datos. Aclare si los datos ya estaban disponibles y si el conjunto de datos se ha explorado o analizado previamente. *
  
Los datos de la primera (2023) y la segunda (2024) ola del estudio panel “Educación y Meritocracia” (EDUMER) ya están disponibles.

No se han realizado análisis previos, más allá de análisis descriptivos y pruebas para evaluar el experimento aplicado.

5. ¿Existe algún criterio de exclusión para los datos?

*Especifique si hubo algún criterio para la exclusión de ciertos conjuntos de datos, observaciones o puntos de tiempo.* 

Se excluirán los casos con respuestas incompletas (datos perdidos y/o NA). Adicionalmente, a través del paquete estadístico de R responsePatterns, es posible detectar patrones de respuesta repetitivos, lo que contribuye a obtener datos de investigación de mayor calidad [@gottfried_autocorrelation_2022]. Por ejemplo, se excluirán casos donde solo se elija la opción “1” o patrones como “1-2-3-4-1-2-3-4.”.

6. ¿Cuáles son los análisis estadísticos previstos?

*Especifique el modelo estadístico que se utilizará para analizar los datos y describa los pasos previos al procesamiento de los datos. Sea lo más específico posible y evite la ambigüedad. *

Antes del análisis de datos, se recodificarán las variables de interés y se eliminarán los casos perdidos y los patrones de respuesta atípicos o problemáticos.

Primero, se realizará un análisis descriptivo univariado. Posteriormente, se efectuarán análisis bivariados (correlacionales). Por último, se aplicarán modelos de regresión multinivel longitudinal, considerando a las personas como la unidad de agrupación.

7. ¿Cuáles son los criterios para confirmar y refutar las hipótesis?

*Especifique exactamente cómo se evaluará la hipótesis. Proporcione criterios específicos relevantes para el marco y modelo analítico utilizado (por ejemplo, valores alfa, factor de Bayes, RMSEA). *

Efectos estadísticamente significativos a un nivel alfa = 0.05 (p\<0.05)

8. ¿Se han validado los análisis en un subconjunto de los datos?

*En caso afirmativo, especifique y proporcione los archivos pertinentes. Indique si los análisis de datos propuestos se han validado previamente en un subconjunto de los datos o en un conjunto de datos simulado. Si es así, proporcione los archivos de datos y la sintaxis de los datos. *

No se han validado análisis hasta el momento.

9. ¿Qué se sabe acerca de los datos que podrían ser relevantes para las hipótesis probadas?

*Describa cualquier conocimiento previo que tenga sobre el conjunto de datos (por ejemplo, la media conocida de una variable) que sea relevante para su pregunta de investigación. *

Se conocen los estadísticos descriptivos básicos de las variables a utilizar (media, moda y frecuencias)

10. Proporcione un breve cronograma de los diferentes pasos del registro previo.
    
*Proporcione las fechas (previstas) para los diferentes pasos en este formulario de preinscripción.*

-   15 de febrero: Primer borrador
