---
title: "descriptivos"
format: html
editor: source
bibliography: "../input/bib/merit-redis-school.bib"
---

```{r, data,echo=FALSE, include=FALSE}
pacman::p_load(dplyr, sjPlot, stargazer, kableExtra, texreg, haven, sjlabelled, ggplot2, summarytools, ggtext, ggpubr, hrbrthemes, tidyr, stringr)

load(here::here("input/data/proc/ola1.RData"))
```

```{r, preparacion, echo=FALSE, eval=TRUE}
#Base General con el cuestionario para estudiantes
#Codificamos los valores 99-88 como missing para todas las variables
proc_datos <- proc_datos %>% set_na(., na = c(99, 88))

for (i in names(dplyr::select(proc_datos, tidyselect::starts_with("p1_"), starts_with("p2_"), starts_with("p8_"), starts_with("p9_"), starts_with("p17_")))) {
  proc_datos[[i]] <- sjlabelled::set_labels(
    x = proc_datos[[i]],
    labels = c("Muy en desacuerdo", "Desacuerdo", "De acuerdo", "Muy de acuerdo")
  )
}


for (i in names(dplyr::select(proc_datos, tidyselect::starts_with("p10_")))) {
  proc_datos[[i]] <- sjlabelled::set_labels(
    x = proc_datos[[i]],
    labels = c("Nada importante", "Algo importante", "Importante", "Muy importante")
  )
}


for (i in names(dplyr::select(proc_datos, tidyselect::starts_with("p11_")))) {
  proc_datos[[i]] <- sjlabelled::set_labels(
    x = proc_datos[[i]],
    labels = c("Seguro no haré esto", "Tal vez haré esto", "Probablemente haré esto", "Seguro haré esto")
  )
}

for (i in names(dplyr::select(proc_datos, tidyselect::starts_with("p12_")))) {
  proc_datos[[i]] <- sjlabelled::set_labels(
    x = proc_datos[[i]],
    labels = c("Si", "No")
  )
}

for (i in names(dplyr::select(proc_datos, tidyselect::starts_with("p13_")))) {
  proc_datos[[i]] <- sjlabelled::set_labels(
    x = proc_datos[[i]],
    labels = c("Nunca", "Una vez al año", "Una vez al mes", "Semanalmente", "Todos los días")
  )
}


for (i in names(dplyr::select(proc_datos, tidyselect::starts_with("p18_")))) {
  proc_datos[[i]] <- sjlabelled::set_labels(
    x = proc_datos[[i]],
    labels = c("Nunca", "Casi nunca", "Casi siempre", "Siempre")
  )
}

```

# Seleccion variables

```{r}
data <- proc_datos %>% select("redistribucion"=p9_2, 
                              tidyselect::starts_with("merit"), 
                              tidyselect::starts_with("school"), 
                              tidyselect::starts_with("social"))

data <- data %>% select(redistribucion, 
                        merit_esfuerzo_percep_ES, merit_esfuerzo_pref_ES, 
                        merit_talento_percep_ES, merit_talento_pref_ES,
                        social_merito_percep_ES, social_merit_pref_ES,
                        school_esfuerzo_ES, school_talento_ES, school_merito_ES)
```

```{r}
print(summarytools::dfSummary(data), method="render")
```

