---
format: 
  html: 
    code-fold: true
    html-math-method: katex
  pdf: 
    geometry: 
      - top=30mm
      - left=20mm
    template-partials: 
      - title.tex
    include-in-header:
      text: |
        \usepackage[noblocks]{authblk}
        \renewcommand*{\Authsep}{, }
        \renewcommand*{\Authand}{, }
        \renewcommand*{\Authands}{, }
        \renewcommand\Affilfont{\small}
editor: source
bibliography: "../../input/bib/merit-redis-school.bib"
author:
  - name: Juan Carlos Castillo
    corresponding: true
    orcid: 0000-0003-1265-7854
    email: juancastillov@uchile.cl
    affiliations:
      - ref: 1
      - ref: 2
      - ref: 3
  - name: Kevin Carrasco
    orcid: 0000-0002-9348-8361
    email: kevin.carrasco@ug.uchile.cl
    affiliations:
      - ref: 2
  - name: Andreas Laffert
    orcid: 0000-0002-9008-2454
    email: kevin.carrasco@ug.uchile.cl
    affiliations:
      - ref: 4
  - name: María Fernanda Núñez
    orcid: 0009-0004-7559-9959
    email: maria.nunez.2@ug.uchile.cl
    affiliations:
      - ref: 1
affiliations: 
  - id: 1
    name: Universidad de Chile
  - id: 2
    name: Centro de estudios del conflicto y cohesión social (COES)
  - id: 3
    name: Núcleo milenio de desigualdades y oportunidades digitales (NUDOS)
  - id: 4
    name: Pontificia Universidad Católica de Chile
lang: es
citeproc: true
---

# Cambio en las creencias sobre meritocracia y redistribución en el contexto escolar

## Abstract

Los crecientes niveles de desigualdad económica y concentración de ingresos han impulsado en los últimos años la investigación sobre las preferencias por la redistribución económica [@becker_significant_2021; @rueda_who_2019], entendidas como aquellas creencias sobre la necesidad de transferencias económicas hacia quienes poseen menos, por lo general a través del Estado. Sin embargo, hasta ahora la mayor parte de las investigaciones sobre preferencias redistributivas se han efectuado en población adulta, dejando de lado el estudio de los factores asociados a estas preferencias en edades más tempranas, así como también su formación. Utilizando datos de la encuesta panel Educación y Meritocracia (N=900, año 2023-2024) de educación básica y media en Chile, el presente estudio ahonda en el cambio de las percepciones y preferencias de la meritocracia en la escuela y la sociedad sobre las preferencias por la redistribución. Dado que la meritocracia se concibe como un sistema donde las recompensas se distribuyen según el esfuerzo y el talento individual [@young_rise_1958], la hipótesis central es que quienes perciban que existe más meritocracia en la escuela y en la sociedad, tenderán a mostrar menores preferencias por el rol del gobierno en la redistribución al existir las condiciones sociales que permitirían la consecución de logros individuales. 

En lo que respecta a la operacionalización de meritocracia, se considerarán dos aspectos en su conceptualización y medición. En primer lugar, la percepción de meritocracia escolar, asociada a que la inteligencia y el esfuerzo son relevantes para obtener buenas calificaciones en la escuela [@resh_sense_2010]. En segundo lugar, se incluirá una medición de meritocracia en la sociedad, que también se divide en dos aspectos. Por un lado, la percepción de meritocracia, es decir, en qué medida se percibe que los esfuerzos y habilidades son recompensados en el país [@andersen_we_2021; @castillo_meritocracia_2019; @mijs_paradox_2019] y, por otro lado, las preferencias por la meritocracia, es decir, en qué medida la meritocracia es deseada en la sociedad [@castillo_multidimensional_2023]. De esta forma, se plantean las siguientes hipótesis:

H1: Estudiantes que presentan mayor percepción de meritocracia en la escuela tendrán menor preferencia por la redistribución.

H2: Estudiantes que presentan mayor percepción de meritocracia en la sociedad tendrán menor preferencia por la redistribución.

H3: Estudiantes que presentan mayor preferencia por la meritocracia en la sociedad tendrán menor preferencia por la redistribución.

Finalmente, investigaciones han demostrado que los niños más pequeños muestran una preferencia por la igualdad, mientras que los niños mayores comienzan a aceptar la desigualdad si esta se justifica por el mérito [@almas_fairness_2010; @baumard_preschoolers_2012]. Por lo tanto, es de esperar que existan diferencias en las preferencias por la redistribución tanto por el nivel escolar (básica o media) como también un cambio a través del tiempo (2023-2024). Por lo tanto, se plantean dos hipótesis adicionales:

H4: Estudiantes de educación media tendrán menor preferencia por la redistribución que estudiantes de educación básica

H5: A medida que los/as estudiantes avanzan en su escolarización, se espera que las preferencias por la redistribución disminuyan.

La base de datos a utilizar corresponde a la encuesta panel "Educación y Meritocracia" (EDUMER), realizada en Chile durante el 2023 y 2024. En este estudio se evaluaron estudiantes de sexto básico y primero medio provenientes de 9 escuelas de la región metropolitana. El N total de respuestas completas es de 902 estudiantes. La variable dependiente de preferencias redistributivas fue medida a partir de la pregunta "El gobierno de Chile debería hacer algo para reducir las brechas de ingresos entre ricos y pobres", con una escala likert de 4 categorías desde "Muy en desacuerdo" a "Muy de acuerdo".

Los resultados muestran que estudiantes con mayor percepción y preferencias por la meritocracia en la sociedad y en la escuela manifiestan menores preferencias por la reducción de brechas económicas entre ricos y pobres. Asimismo, los estudiantes de educación media tienen menores preferencias por la redistribución que los estudiantes de educación básica. Se discuten las implicancias de estos resultados para la socialización política de estudiantes por parte de la familia de origen y la escuela. 


```{r}
#| echo: false
#| label: wordstats
#| warning: false
#| message: false
wordcount <- wordcountaddin::text_stats('abstract.qmd')
words <- substr(wordcount[3], start=19, stop=29)
```

**Word count**: `r words`
